GENRES = {
    'fantasy': 'Фэнтези',
    'romance': 'Романтика',
    'adventure': 'Приключения',
    'mystery': 'Детектив',
    'horror': 'Ужасы',
    'scifi': 'Научная фантастика',
    'historical': 'Исторический',
    'contemporary': 'Современный',
    'paranormal': 'Паранормальное',
    'urban': 'Городское фэнтези',
    'litrpg': 'ЛитРПГ',
    'isekai': 'Исекай',
    'reincarnation': 'Реинкарнация',
    'magic': 'Магия',
    'supernatural': 'Сверхъестественное',
    'mythology': 'Мифология',
    'dystopian': 'Антиутопия',
    'post_apocalyptic': 'Постапокалипсис',
    'psychological': 'Психологический',
    'thriller': 'Триллер',
    'mystical': 'Мистика',
    'vampires': 'Вампиры',
    'werewolves': 'Оборотни',
    'demons': 'Демоны',
    'angels': 'Ангелы',
    'gods': 'Боги',
    'monsters': 'Монстры',
    'magical_realism': 'Магический реализм',
    'portal_fantasy': 'Портал фэнтези',
    'time_travel': 'Путешествия во времени',
    'alternate_history': 'Альтернативная история',
    'steampunk': 'Стимпанк',
    'cyberpunk': 'Киберпанк',
    'drama': 'Драма',
    'comedy': 'Комедия',
    'slice_of_life': 'Повседневность',
    'military': 'Военное',
    'martial_arts': 'Боевые искусства',
    'cultivation': 'Культивация',
    'xianxia': 'Сянься',
    'wuxia': 'Уся',
    'harem': 'Гарем',
    'reverse_harem': 'Обратный гарем',
    'shoujo': 'Сёдзё',
    'shounen': 'Сёнен',
    'seinen': 'Сэйнэн',
    'josei': 'Дзёсэй',
    'yaoi': 'Яой',
    'yuri': 'Юри',
    'gender_bender': 'Смена пола',
    'crossdressing': 'Кроссдрессинг',
    'school_life': 'Школьная жизнь',
    'college_life': 'Студенческая жизнь',
    'office_life': 'Офисная жизнь',
    'game': 'Игры',
    'virtual_reality': 'Виртуальная реальность',
    'sports': 'Спорт',
    'music': 'Музыка',
    'art': 'Искусство',
    'cooking': 'Кулинария',
    'medical': 'Медицина',
    'law': 'Право',
    'politics': 'Политика',
    'economics': 'Экономика',
    'philosophy': 'Философия',
    'religion': 'Религия',
    'mythology': 'Мифология',
    'folklore': 'Фольклор',
    'fairy_tale': 'Сказка',
    'fable': 'Басня',
    'poetry': 'Поэзия',
    'essay': 'Эссе',
    'biography': 'Биография',
    'autobiography': 'Автобиография',
    'memoir': 'Мемуары',
    'travel': 'Путешествия',
    'guide': 'Руководство',
    'textbook': 'Учебник',
    'reference': 'Справочник',
    'dictionary': 'Словарь',
    'encyclopedia': 'Энциклопедия',
    'atlas': 'Атлас',
    'almanac': 'Альманах',
    'calendar': 'Календарь',
    'diary': 'Дневник',
    'journal': 'Журнал',
    'letter': 'Письмо',
    'speech': 'Речь',
    'sermon': 'Проповедь',
    'prayer': 'Молитва',
    'ritual': 'Ритуал',
    'spell': 'Заклинание',
    'curse': 'Проклятие',
    'blessing': 'Благословение',
    'prophecy': 'Пророчество',
    'divination': 'Гадание',
    'astrology': 'Астрология',
    'alchemy': 'Алхимия',
    'herbalism': 'Травничество',
    'healing': 'Исцеление',
    'necromancy': 'Некромантия',
    'summoning': 'Призыв',
    'enchantment': 'Зачарование',
    'illusion': 'Иллюзия',
    'transmutation': 'Трансмутация',
    'conjuration': 'Вызов',
    'abjuration': 'Ограждение',
    'evocation': 'Воплощение',
    'divination': 'Прорицание',
    'transformation': 'Превращение',
    'possession': 'Одержимость',
    'exorcism': 'Изгнание',
    'resurrection': 'Воскрешение',
    'immortality': 'Бессмертие',
    'reincarnation': 'Реинкарнация',
    'afterlife': 'Загробная жизнь',
    'heaven': 'Рай',
    'hell': 'Ад',
    'purgatory': 'Чистилище',
    'limbo': 'Лимб',
    'valhalla': 'Вальхалла',
    'elysium': 'Элизиум',
    'tartarus': 'Тартар',
    'asgard': 'Асгард',
    'midgard': 'Мидгард',
    'alfheim': 'Альфхейм',
    'svartalfheim': 'Свартальфхейм',
    'niflheim': 'Нифльхейм',
    'muspelheim': 'Мусспельхейм',
    'jotunheim': 'Ётунхейм',
    'vanaheim': 'Ванахейм',
    'nidavellir': 'Нидавеллир',
    'valinor': 'Валинор',
    'middle_earth': 'Средиземье',
    'narnia': 'Нарния',
    'wonderland': 'Страна чудес',
    'neverland': 'Нетландия',
    'oz': 'Страна Оз',
    'atlantis': 'Атлантида',
    'el_dorado': 'Эльдорадо',
    'shambhala': 'Шамбала',
    'agartha': 'Агарта',
    'hyperborea': 'Гиперборея',
    'lemuria': 'Лемурия',
    'mu': 'Му',
    'arcadia': 'Аркадия',
    'utopia': 'Утопия',
    'dystopia': 'Антиутопия',
    'paradise': 'Рай',
    'eden': 'Эдем',
    'olympus': 'Олимп',
    'pantheon': 'Пантеон',
    'valhalla': 'Вальхалла',
    'elysium': 'Элизиум',
    'tartarus': 'Тартар',
    'asgard': 'Асгард',
    'midgard': 'Мидгард',
    'alfheim': 'Альфхейм',
    'svartalfheim': 'Свартальфхейм',
    'niflheim': 'Нифльхейм',
    'muspelheim': 'Мусспельхейм',
    'jotunheim': 'Ётунхейм',
    'vanaheim': 'Ванахейм',
    'nidavellir': 'Нидавеллир',
    'valinor': 'Валинор',
    'middle_earth': 'Средиземье',
    'narnia': 'Нарния',
    'wonderland': 'Страна чудес',
    'neverland': 'Нетландия',
    'oz': 'Страна Оз',
    'atlantis': 'Атлантида',
    'el_dorado': 'Эльдорадо',
    'shambhala': 'Шамбала',
    'agartha': 'Агарта',
    'hyperborea': 'Гиперборея',
    'lemuria': 'Лемурия',
    'mu': 'Му',
    'arcadia': 'Аркадия',
    'utopia': 'Утопия',
    'dystopia': 'Антиутопия',
    'paradise': 'Рай',
    'eden': 'Эдем',
    'olympus': 'Олимп',
    'pantheon': 'Пантеон'
} 